### GET hero
GET http://127.0.0.1:8000/api/heroes
Accept: application/json

### Send POST request with json body
POST http://127.0.0.1:8000/api/heroes
Content-Type: application/json

{
    "id": 999
}
